basePath: /
definitions:
  dto.CreateUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.UserLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  response.BaseErrorResponse:
    properties:
      code:
        type: integer
      error: {}
      status:
        type: string
    type: object
  response.BaseSuccessResponse:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Canonflow API documentation
  title: Canonflow API
  version: "1.0"
paths:
  /api/v1/auth/me:
    get:
      consumes:
      - application/json
      description: get user information for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
      summary: Get user information
      tags:
      - auth
  /api/v1/auth/signin:
    post:
      consumes:
      - application/json
      description: sign in to an existing account with the provided information
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
      summary: Sign in to an existing account
      tags:
      - auth
  /api/v1/auth/signout:
    post:
      consumes:
      - application/json
      description: sign out of the current account and invalidate the access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
      summary: Sign out of the current account
      tags:
      - auth
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: create a new account with the provided information
      parameters:
      - description: User information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseErrorResponse'
      summary: Create an account
      tags:
      - auth
swagger: "2.0"
